Implementing file storage via Amazon S3
Konstantsiy/image-converter pull request #10
Opened 2021-07-05 15:13 UTC by Konstantsiy

2021-08-11 14:42 UTC, papahmsolo requested changes
👍

2021-08-11 14:42 UTC, papahmsolo commented on internal/app/app.go
> +	}
Wrap error with some context

2021-08-11 14:42 UTC, papahmsolo commented on internal/storage/storage.go
> +}
- validate config values
- create session/client

2021-08-11 14:42 UTC, papahmsolo commented on internal/storage/storage.go
> +	fileLocation := fmt.Sprintf(LocationTemplate, s.s3conf.Region, s.s3conf.BucketName, secretFileKey.String())
get image id as a param

2021-08-12 10:45 UTC, Konstantsiy commented on internal/storage/storage.go
> +	fileLocation := fmt.Sprintf(LocationTemplate, s.s3conf.Region, s.s3conf.BucketName, secretFileKey.String())
> get image id as a param

ok, we'll have to simplify it

2021-08-17 08:22 UTC, papahmsolo reviewed
👍

2021-08-17 08:22 UTC, papahmsolo approved these changes

2021-08-17 08:22 UTC, merged